export const endpoints = {
  liveCameras: '/v1/live/cameras',
  violations: '/v1/violations',
  violationById: (id: string) => `/v1/violations/${id}`,
  violationEvidenceUrl: (id: string) => `/v1/violations/${id}/evidence-url`,
  violationChallanDownload: (id: string) => `/v1/violations/${id}/challan/download`,
  challans: '/v1/challans',
  challanById: (id: string) => `/v1/challan/${id}`,
  challanPdf: (id: string) => `/v1/challan/${id}/pdf`,
  challanImage: (id: string) => `/v1/challan/${id}/image`,
  challansBulkExport: '/v1/challans/export',
  dashboardSummary: '/v1/violations/summary',
  alerts: '/v1/alerts',
  edgeRuntimeStatus: '/v1/edge/live-preview',
  edgeRuntimeFrame: '/v1/edge/live-preview/frame',
  edgeConfig: '/v1/edge/config',
} as const
